### ISSUE TITLE
java.lang.IllegalArgumentException: You must provide either an `:xpath` or `:css` entry.

### ISSUE THREAD

**Issue by thurmondmb** [semperos/clj-webdriver#144]
I can navigate to a page by using the following:

(set-driver {...})
(quick-fill-submit {....})
(click "a[href*='/path/']")

then when I include 

(click (find-element {:xpath "/html/..."}))

I get the following error: CompilerException java.lang.IllegalArgumentException: You must provide either an `:xpath` or `:css` entry.

I then copy and paste (click (find-element {:xpath "/html/..."})) and run that in the repl and it does what I want it to.  

Does anyone know why I'm getting this error?

Thanks!

**Comment by decoursin** [comment]
Did you figure it out?
