### ISSUE TITLE
ClassNotFoundException when setting chrome driver with additional phantomjsdriver dependency

### ISSUE THREAD

**Issue by axsk** [semperos/clj-webdriver#147]
When adding the phantomjsdriver dependency to the project.clj, starting `lein repl` and evaluating `(clj-webdriver.taxi/set-driver! {:browser :chrome})` I receive the following exception:

```ClassNotFoundException org.openqa.selenium.remote.service.DriverService$Builder  java.net.URLClassLoader.findClass (URLClassLoader.java:381)```

The phantomjs driver works flawlessly. 
When removing the phantomjsdriver dependency and repeating these steps the chrome driver works as well.

So it seems somehow adding phantomjsdriver breaks the chrome driver :(

I am using ```[[org.clojure/clojure "1.7.0"]
[clj-webdriver "0.7.2"]
[org.seleniumhq.selenium/selenium-java "2.47.1"]
[com.codeborne/phantomjsdriver "1.2.1"]]```

**Comment by semperos** [comment]
@axsk Could you please paste here the output of running `lein deps :tree` both with and then without the PhantomJS driver JAR in your dependencies? Thanks.

**Comment by axsk** [comment]
You had the right nose here. The problem arised by phantomjs overwriting the dependency on version of `selenium-remote-driver 2.47.1` with version `2.44.0` ([output](https://gist.github.com/axsk/d5307931be84afb2ac27))

I guess downgrading `selenium-java` to 2.44.0 would fix this, but I was greedy excluding the stale dependency from `phantomjsdriver` (in hope no breaking changes happend from 2.44->2.47.1). As far as I can tell both browsers work just fine.

Thank you for the advice and excuse the noise :)

**Comment by semperos** [comment]
@axsk Thanks for reporting back with your findings. I think I'll add a page to this project's wiki that goes into more details about this kind of problem, since it comes up fairly frequently.

**Comment by semperos** [comment]
I'll add it to a PhantomJS-specific section at some point, but for now I've written this up:

https://github.com/semperos/clj-webdriver/wiki/Clojure-and-Java-Dependencies#dependency-resolution-problems

**Comment by axsk** [comment]
Amazing work, thank you! *Thumbs Up*
