### ISSUE TITLE
java.lang.ClassNotFoundException: org.openqa.selenium.interactions.Actions

### ISSUE THREAD

**Issue by robbieh** [semperos/clj-webdriver#150]
It's pretty simple...
`lein new test-project`
and then add `[clj-webdriver "0.7.2"]` to project.clj.
Start a repl.
```
user=> (use 'clj-webdriver.taxi)

CompilerException java.lang.ClassNotFoundException: org.openqa.selenium.interactions.Actions, compiling:(clj_webdriver/driver.clj:1:1) 
```

**Comment by semperos** [comment]
@robbieh What does your project.clj look like? As mentioned [in the README](https://github.com/semperos/clj-webdriver#clojure-api-for-selenium-webdriver) you have to specify the Selenium-WebDriver JAR's you need explicitly. This allows folks to use the versions of those JAR's that support the browsers they target.

**Comment by robbieh** [comment]
Thanks for pointing that out. I had jumped from an 0.6 version to the most recent, and then went back and was reading the Wiki. I missed that change in the README. My apologies. It is working fine now!

**Comment by semperos** [comment]
No worries, it prompted me to review the Wiki and fill in a page related to this that I had only stubbed out before: https://github.com/semperos/clj-webdriver/wiki/ClassNotFoundException.

**Comment by robbieh** [comment]
Thanks! That is helpful info. It might be nice to make a note from the Taxi page, or maybe add something to the README where you show the current version for project.clj. Like maybe:

```
 [clj-webdriver "0.7.2"]
 ;The Selenium Webdriver jars must be explicitly included
 ;see: https://github.com/semperos/clj-webdriver/wiki/ClassNotFoundException
 ;for example:
 [org.seleniumhq.selenium/selenium-java "2.47.1"]
```
Though I completely understand that I am an airhead and simply missed the very thing I was looking for.
